### PR TITLE
Feature/ti 2497 season editor editable test items ids

### PR DESCRIPTION
**Pull request by bartosz-bujakowski**
This PR adds:
- Editable test item id
- Validation for duplicate test item ids
- Adds react-hot-toast for displaying global errors

### CODE REVIEW

**Review by eickler — APPROVED** [review]
[c] Looks good. Maybe a little bit more directive error message to tell the user what to do? Like "Error: Please review your test items and make sure that each test item has a different ID." (Maybe @ryanoshea-td has a good sentence.)

**Comment by ryanoshea-td** [comment]
> [c] Looks good. Maybe a little bit more directive error message to tell the user what to do? Like "Error: Please review your test items and make sure that each test item has a different ID." (Maybe @ryanoshea-td has a good sentence.)

What about?

Error: Duplicate Test ID. Please make sure your Test IDs are unique for this season.

**Review by ryanoshea-td — CHANGES_REQUESTED** [review]
[c] Looks good to me but I saw some layout issues that are not related to the PR but should probably be looked at. Perhaps in another ticket and not in this PR. 

[q] but why is hot-toast preferred over MUI snackbar? I saw you had snack bar in there but removed it.

[M] I noticed a layout bug. When the editor is loaded or the page is refreshed the inputs can overlap the sidebar. 

Screenshot 2023-12-20 at 11 51 34
Screenshot 2023-12-20 at 11 52 41

[m] The editor doesn't isn't responsive. I would prefer that the panels didn't run off the end of the screen. 

Screenshot 2023-12-20 at 12 08 55

**Comment by bartosz-bujakowski** [comment]
> [q] but why is hot-toast preferred over MUI snackbar? I saw you had snack bar in there but removed it.

Ease of use. With RHT we can just do `toast("blabla")`. With snackbar you would need to add your own service for that. Snackbar by default needs to be implemented in each component separately :/

> [c] Looks good to me but I saw some layout issues that are not related to the PR but should probably be looked at. Perhaps in another ticket and not in this PR.
> [M] I noticed a layout bug. When the editor is loaded or the page is refreshed the inputs can overlap the sidebar.
> [m] The editor doesn't isn't responsive. I would prefer that the panels didn't run off the end of the screen.

Yes, I didn't really add any mobile/RWD support because I thought it's a desktop only tool. Was way easier to not implement it in the previous designs but now I think I've managed to add basic mobile support with a few lines of changes so definitely worth it. It seems that the change also fixed the refresh issue. Thanks for pointing the issue out. If you think it's worth expanding mobile support we can add a task for that.

**Comment by eickler** [comment]
> Yes, I didn't really add any mobile/RWD support because I thought it's a desktop only tool. Was way easier to not implement it in the previous designs but now I think I've managed to add basic mobile support with a few lines of changes so definitely worth it. It seems that the change also fixed the refresh issue. Thanks for pointing the issue out. If you think it's worth expanding mobile support we can add a task for that.

I would tend to agree to that. At least I wouldn't like to type test items, descriptions etc without a keyboard.

**Comment by ryanoshea-td** [comment]
> > [q] but why is hot-toast preferred over MUI snackbar? I saw you had snack bar in there but removed it.
> 
> Ease of use. With RHT we can just do `toast("blabla")`. With snackbar you would need to add your own service for that. Snackbar by default needs to be implemented in each component separately :/

Ah! Thanks!

 
> > [c] Looks good to me but I saw some layout issues that are not related to the PR but should probably be looked at. Perhaps in another ticket and not in this PR.
> > [M] I noticed a layout bug. When the editor is loaded or the page is refreshed the inputs can overlap the sidebar.
> > [m] The editor doesn't isn't responsive. I would prefer that the panels didn't run off the end of the screen.
> 
> Yes, I didn't really add any mobile/RWD support because I thought it's a desktop only tool. Was way easier to not implement it in the previous designs but now I think I've managed to add basic mobile support with a few lines of changes so definitely worth it. It seems that the change also fixed the refresh issue. Thanks for pointing the issue out. If you think it's worth expanding mobile support we can add a task for that.

This looks much better 👍 
And I don't think mobile support is needed either.  

Screenshot 2023-12-20 at 14 37 33

**Review by ryanoshea-td — APPROVED** [review]

**Pull request merged**
